
services:
  # 1. Zookeeper - Necessário para o Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181" # Porta padrão do Zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - chat4all_net

  # 2. Kafka - Broker de mensageria
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # Listener interno (para outros containers Docker)
      - "29092:29092" # Listener externo (para sua aplicação rodando no localhost)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Define como o Kafka pode ser acessado de dentro e de fora do Docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - chat4all_net

  # 3. Cassandra - Message Store DB
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042" # Porta padrão do Cassandra (CQL)
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      # Verifica se o cqlsh (shell do Cassandra) consegue conectar
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - chat4all_net
  
  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy # Espera o healthcheck do cassandra dar OK
    volumes:
      - ./scripts/init_cassandra.cql:/init.cql # Injeta o script dentro do container
    networks:
      - chat4all_net
    # Comando: Conecta no host 'cassandra' e roda o arquivo
    command: cqlsh cassandra -f /init.cql

  # 4. CockroachDB - Metadata DB
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    # Inicia um cluster de nó único sem segurança (ideal para dev local)
    command: start-single-node --insecure
    ports:
      - "26257:26257" # Porta padrão do CockroachDB (SQL)
      - "8080:8080"   # Porta da Admin UI
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
    healthcheck:
      # Verifica se a UI de saúde está respondendo
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat4all_net

  #.5 Frontend-service
  frontend_service:
    build:
      context: ./frontend_service  # Caminho para a pasta com o Dockerfile
    container_name: frontend_service_c
    ports:
      - "8000:8000"  # Expõe a porta 8000 do contêiner para a porta 8000 do seu PC
    depends_on:
      kafka:
        condition: service_started # <-- Novo (bom para o Kafka)
      cassandra:
        condition: service_healthy        # Garante que o Kafka suba antes da API
    networks:
      - chat4all_net # IMPORTANTE: Coloque na mesma rede dos outros serviços
    environment:
      - CASSANDRA_HOSTS=cassandra
      - MINIO_URL=http://minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - TZ=America/Sao_Paulo
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - REDIS_URL=redis://redis:6379/0

  # -----------------------------------------------
  # 6. ROUTER WORKER (CONSUMIDOR) <--- NOVO SERVIÇO
  # -----------------------------------------------
  router_worker:
    build:
      context: ./services/router_worker # 1. Aponta para a pasta do worker
    #container_name: router_worker_c
    deploy:
      replicas: 2
    depends_on:
      - kafka # 2. Só inicia depois do Kafka
      - cassandra-init        
      - cassandra     # 3. Só inicia depois do Cassandra
    environment:
      # 4. Injeta as variáveis de ambiente que o worker.py precisa
      - KAFKA_BROKER_URL=kafka:9092   # Conexão INTERNA com o Kafka
      - CASSANDRA_HOSTS=cassandra     # Conexão INTERNA com o Cassandra
      - CASSANDRA_KEYSPACE=chat4all_ks
      - KAFKA_TOPIC=chat_messages
      - TZ=America/Sao_Paulo
      - REDIS_URL=redis://redis:6379/0
    networks:
      - chat4all_net # 5. Coloca na mesma rede de todos os outros

  # -----------------------------------------------
  # 7. METADATA SERVICE (NOVO)
  # -----------------------------------------------
  metadata_service:
    build:
      context: ./services/metadata_service
    container_name: metadata_service_c
    ports:
      - "8001:8001"  # Expõe na porta 8001 (diferente da API de mensagens 8000)
      - "50051:50051"
    depends_on:
      cockroachdb:
        condition: service_healthy  # Só inicia depois do banco
    environment:
      # AQUI ESTÁ O SEGREDO:
      # Mudamos de 'localhost' para 'cockroachdb' (nome do serviço)
      - DATABASE_URL=cockroachdb://root@cockroachdb:26257/defaultdb?sslmode=disable
      - TZ=America/Sao_Paulo
    networks:
      - chat4all_net

  connector_whatsapp:
    build: ./services/connector_whatsapp
    container_name: connector_whatsapp_c
    depends_on:
      kafka:
        condition: service_started
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - TZ=America/Sao_Paulo
    networks:
      - chat4all_net
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - TZ=America/Sao_Paulo
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - chat4all_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - chat4all_net
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/chat-files;
      /usr/bin/mc anonymous set public myminio/chat-files;
      exit 0;
      "
  
  connector_instagram:
    build: ./services/connector_instagram
    container_name: connector_instagram_c
    depends_on:
      kafka:
        condition: service_started
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - TZ=America/Sao_Paulo
    networks:
      - chat4all_net

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      networks:
        - chat4all_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha padrão para facilitar
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - "chat4all_net"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chat4all_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  connector_telegram:
      build: ./services/connector_telegram
      container_name: connector_telegram
      depends_on:
        kafka:
          condition: service_started
      environment:
        - KAFKA_BROKER_URL=kafka:9092
        - TELEGRAM_TOKEN=8578098550:AAEmwz6XaOdJrW4JXimxPqk5VNK0FHEmIu0 # <--- COLOQUE O TOKEN
      networks:
        - chat4all_net

  jaeger:
      image: jaegertracing/all-in-one:1.50
      container_name: jaeger
      ports:
        - "16686:16686" # Interface Web
        - "4317:4317"   # OTLP gRPC receiver
      networks:
        - chat4all_net

# Definição dos volumes para persistir os dados
volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  cassandra_data:
  cockroachdb_data:
  minio_data:
  grafana_data:

networks:
  chat4all_net:
    driver: bridge